Adds docs on how to enable Live Reload in a starter app
codeforamerica/form-flow-starter-app pull request #252
Opened 2023-11-15 23:14 UTC by coltborg

[#183429068](https://www.pivotaltracker.com/story/show/183429068)

This feature is really a configuration change in IntelliJ. Code wise, I documented the steps and then removed some application configuration that isn't needed as it wasn't contributing to allowing Live Reload to work.

2023-11-16 20:44 UTC, enyia21 requested changes
There is only one change that I'd like to see made

2023-11-16 20:44 UTC, enyia21 commented on README.md
> +* Go to `http://localhost:8080/`
Should we alert developers that they need to start up their applications before visiting `http://localhost:8080`?

2023-11-16 23:16 UTC, coltborg commented on README.md
> +* Go to `http://localhost:8080/`
I moved around the structure so that it makes more sense, to your point. Thank you!

2023-11-17 15:47 UTC, enyia21 approved these changes
Great

2023-11-17 15:48 UTC, merged